/*

функция цикла for 
const calendarFiftenMins = [                
    '[title="чт, 21 янв."] > [num="10"] > [title="10:45"]',
    '[title="чт, 21 янв."] > [num="10"] > [title="10:30"]',
    '[title="чт, 21 янв."] > [num="10"] > [title="10:15"]',
    '[title="чт, 21 янв."] > [num="10"] > [title="10:00"]',
];
calendarFiftenMins.forEach(function(item) {
    cy.get(item).click();
});

-------------------------------------------------------
'[title="чт, 21 янв."] [title="10:00"] [data-value="00:00"]'-этот код для проверки селекта выбранного времени в модалке расписания 


// cy.get('[title="сюда вносим дату в формате(пн, 25 янв.)"] > [num="сюда вносим номер слота в формате(23)"] > [title="сюда вносим время слота в формате(23:00)"]')
//все вводы вносим без скобок!!!

 //на этом(где нужно изменить дату и время на аутуальные) шаге нужно прописать логику открытия модалки. Выбираем нужный нам запрос по слледущим критериям
        //1- слот не должен быть прощедщего дня или прошедшего времени
        //2-в прописанной команде должен быть слот с датой(желаетльно) на следующие день после указанного в твоём календаре

//добавить кейсы на тесты создание 30,60,120 мунутных слотов
//добавить кейсы по уменьшению времени от начало слота путём открывание списка в модалкае а после уменьшение по 15 минут

        */

const dataSlots = "пт, 29 янв.";

const dataMonday1 = "пн, 25 янв."; //дата понедельника
const dataTuesday2 = "вт, 26 янв."; //дата вторника
const dataWednesday3 = "ср, 27 янв."; //дата среды
const dataThursday4 = "чт, 28 янв."; //дата четверга
const dataFriday5 = "пт, 29 янв."; //дата пятницы
const dataSaturday6 = "сб, 30 янв."; //дата суботы
const dataSunday7 = "вс, 31 янв."; //дата воскресенья



describe('calendar_schedule', () => {
    beforeEach(() => {
        cy.authTutor();
        cy.visit('');
        cy.wait(5000) //тайм аут в 1 секунду = 1000 мили секунд
        cy.get('.next-time').click() //переход на следующую неделю
        cy.wait(5000) //тайм аут в 1 секунду = 1000 мили секунд

    });

    it('click all slots', () => {

        cy.get(`[title="${dataMonday1}"] [title="23:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="22:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="22:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="22:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="22:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="21:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="21:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="21:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="21:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="20:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="20:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="20:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="20:00"]`).click()
        cy.get(`[title="${dataMonday1}"] title="19:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="19:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="19:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="19:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="18:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="18:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="18:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="18:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="17:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="17:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="17:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="17:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="16:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="16.30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="16:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="16:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="15:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="15:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="15:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="15:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="14:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="14:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="14:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="14:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="13:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="13:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="13:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="13:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="12:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="12:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="12:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="12:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="11:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="11:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="11:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="11:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="10:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="10:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="10:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="10:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="9:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="9:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="9:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="9:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="8:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="8:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="8:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="8:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="7:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="7:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="7:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="7:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="6:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="6:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="6:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="6:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="5:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="5:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="5:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="5:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="4:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="4:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="4:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="4:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="3:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="3:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="3:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="3:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="3:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="3:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="3:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="2:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="2:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="2:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="2:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="1:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="1:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="1:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="1:00"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="0:45"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="0:30"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="0:15"]`).click()
        cy.get(`[title="${dataMonday1}"] [title="0:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="23:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="22:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="22:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="22:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="22:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="21:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="21:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="21:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="21:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="20:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="20:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="20:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="20:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="19:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="19:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="19:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="19:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="18:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="18:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="18:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="18:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="17:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="17:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="17:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="17:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="16:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="16:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="16:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="16:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="15:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="15:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="15:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="15:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="14:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="14:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="14:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="14:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="13:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="13:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="13:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="13:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="12:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="12:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="12:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="12:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="11:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="11:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="11:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="11:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="10:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="10:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="10:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="10:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="9:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="9:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="9:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="9:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="8:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="8:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="8:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="8:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="7:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="7:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="7:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="7:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="6:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="6:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="6:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="6:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="5:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="5:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="5:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="5:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="4:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="4:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="4:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="4:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="3:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="3:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="3:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="3:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="2:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="2:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="2:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="2:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="1:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="1:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="1:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="1:00"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="0:45"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="0:30"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="0:15"]`).click()
        cy.get(`[title="${dataTuesday2}"] [title="0:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="23:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="22:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="22:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="22:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="22:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="21:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="21:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="21:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="21:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="20:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="20:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="20:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="20:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="19:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="19:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="19:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="19:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="18:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="18:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="18:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="18:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="17:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="17:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="17:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="17:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="16:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="16:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="16:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="16:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="15:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="15:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="15:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="15:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="14:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="14:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="14:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="14:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="13:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="13:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="13:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="13:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="12:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="12:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="12:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="12:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="11:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="11:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="11:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="11:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="10:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="10:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="10:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="10:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="9:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="9:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="9:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="9:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="8:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="8:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="8:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="8:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="7:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="7:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="7:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="7:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="6:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="6:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="6:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="6:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="5:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="5:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="5:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="5:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="4:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="4:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="4:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="4:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="3:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="3:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="3:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="3:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="2:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="2:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="2:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="2:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="1:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="1:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="1:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="1:00"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="0:45"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="0:30"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="0:15"]`).click()
        cy.get(`[title="${dataWednesday3}"] [title="0:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="23:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="22:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="22:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="22:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="22:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="21:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="21:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="21:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="21:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="20:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="20:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="20:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="20:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="19:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="19:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="19:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="19:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="18:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="18:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="18:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="18:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="17:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="17:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="17:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="17:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="16:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="16:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="16:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="16:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="15:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="15:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="15:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="15:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="14:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="14:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="14:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="14:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="13:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="13:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="13:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="13:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="12:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="12:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="12:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="12:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="11:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="11:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="11:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="11:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="10:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="10:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="10:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="10:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="9:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="9:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="9:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="9:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="8:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="8:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="8:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="8:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="7:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="7:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="7:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="7:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="6:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="6:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="6:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="6:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="5:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="5:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="5:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="5:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="4:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="4:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="4:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="4:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="3:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="3:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="3:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="3:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="2:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="2:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="2:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="2:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="1:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="1:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="1:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="1:00"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="0:45"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="0:30"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="0:15"]`).click()
        cy.get(`[title="${dataThursday4}"] [title="0:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="23:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="22:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="22:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="22:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="22:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="21:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="21:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="21:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="21:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="20:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="20:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="20:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="20:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="19:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="19:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="19:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="19:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="18:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="18:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="18:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="18:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="17:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="17:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="17:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="17:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="16:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="16:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="16:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="16:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="15:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="15:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="15:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="15:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="14:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="14:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="14:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="14:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="13:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="13:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="13:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="13:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="12:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="12:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="12:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="12:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="11:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="11:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="11:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="11:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="10:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="10:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="10:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="10:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="9:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="9:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="9:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="9:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="8:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="8:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="8:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="8:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="7:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="7:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="7:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="7:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="6:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="6:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="6:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="6:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="5:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="5:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="5:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="5:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="4:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="4:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="4:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="4:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="3:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="3:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="3:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="3:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="2:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="2:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="2:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="2:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="1:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="1:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="1:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="1:00"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="0:45"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="0:30"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="0:15"]`).click()
        cy.get(`[title="${dataFriday5}"] [title="0:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="23:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="22:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="22:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="22:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="22:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="21:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="21:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="21:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="21:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="20:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="20:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="20:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="20:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="19:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="19:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="19:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="19:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="18:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="18:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="18:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="18:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="17:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="17:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="17:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="17:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="16:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="16:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="16:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="16:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="15:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="15:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="15:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="15:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="14:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="14:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="14:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="14:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="13:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="13:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="13:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="13:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="12:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="12:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="12:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="12:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="11:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="11:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="11:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="11:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="10:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="10:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="10:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="10:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="9:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="9:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="9:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="9:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="8:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="8:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="8:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="8:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="7:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="7:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="7:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="7:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="6:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="6:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="6:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="6:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="5:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="5:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="5:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="5:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="4:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="4:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="4:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="4:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="3:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="3:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="3:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="3:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="2:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="2:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="2:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="2:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="1:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="1:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="1:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="1:00"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="0:45"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="0:30"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="0:15"]`).click()
        cy.get(`[title="${dataSaturday6}"] [title="0:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="23:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="22:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="22:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="22:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="22:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="21:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="21:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="21:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="21:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="20:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="20:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="20:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="20:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="19:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="19:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="19:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="19:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="18:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="18:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="18:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="18:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="17:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="17:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="17:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="17:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="16:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="16:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="16:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="16:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="15:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="15:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="15:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="15:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="14:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="14:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="14:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="14:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="13:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="13:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="13:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="13:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="12:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="12:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="12:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="12:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="11:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="11:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="11:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="11:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="10:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="10:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="10:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="10:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="9:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="9:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="9:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="9:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="8:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="8:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="8:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="8:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="7:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="7:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="7:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="7:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="6:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="6:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="6:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="6:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="5:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="5:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="5:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="5:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="4:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="4:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="4:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="4:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="3:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="3:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="3:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="3:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="2:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="2:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="2:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="2:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="1:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="1:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="1:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="1:00"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="0:45"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="0:30"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="0:15"]`).click()
        cy.get(`[title="${dataSunday7}"] [title="0:00"]`).click()

    }) //click all slots(прокликать все слоты в календаре)


    it('time slot', () => {

        cy.get('.next-time').click() //переход на неделю вперёд-2
        cy.get('.next-time').click() //переход на неделю вперёд-3
        cy.get('.next-time').click() //переход на неделю вперёд-4
        cy.get('.next-time').click() //переход на неделю вперёд-5
        cy.get('.prev-time').click() // переход на неделю назад-1
        cy.get('.prev-time').click() // переход на неделю назад-2
        cy.get('.prev-time').click() // переход на неделю назад-3
        cy.get('.prev-time').click() // переход на неделю назад-4
        cy.wait(2000) //тайм аут в 1 секунду = 1000 мили секунд

        //ыбирае из списка переменных например-"${dataSlots}" нужный нам день заранее изменив дату 
        //на валидную в этой переменной

        cy.get('.freeslot-modal-close > .demo-icon').click() //кнопка закрытия модалки     
        cy.get(`[title="${dataSlots}"] [title="12:00"]`).click() //валидная переменная(валидная дата)
        cy.get('.popup-footer-buttons > :nth-child(2)').click // кнопка отмена в модалке
        cy.get(`[title="${dataSlots}"] [title="12:00"]`).click() //валидная переменная(валидная дата)
        cy.get('._yellow').click() //нажимаем на сохранить
        cy.wait(2000) //тайм аут в 1 секунду = 1000 мили секунд
        cy.get(`[title="${dataSlots}"] [title="12:00"]`).click() //валидная переменная(валидная дата)
        cy.get('.btn-popup-delete').click() //удаляем слот времени
        cy.wait(2000) //тайм аут в 1 секунду = 1000 мили секунд
        cy.get(`[title="${dataSlots}"] [title="12:00"]`).click() //валидная переменная(валидная дата)
        cy.get('.freeslot-modal-switcher > :nth-child(2)').click() //кнопка выбора еженедельно
        cy.get('._yellow').click() //нажимаем на сохранить
        cy.wait(2000) //тайм аут в 1 секунду = 1000 мили секунд
        cy.get(`[title="${dataSlots}"] [title="12:00"]`).click() //валидная переменная(валидная дата)
        cy.get('.btn-popup-delete').click() //удаляем слот времени

    }) //time slot - создание разового и еженедельно слота времени в календаре и его удаление


}); //основной